//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.07 at 10:02:09 обнГ CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://services.saicmotor.com/services/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.UNQUALIFIED)
package com.saicmotor.services.services;
